// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/handler.go
//
// Generated by this command:
//
//	mockgen -source internal/handler/handler.go -destination internal/handler/mock_database_test.go -package handler
//

// Package handler is a generated GoMock package.
package handler

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDatabasePinger is a mock of DatabasePinger interface.
type MockDatabasePinger struct {
	ctrl     *gomock.Controller
	recorder *MockDatabasePingerMockRecorder
	isgomock struct{}
}

// MockDatabasePingerMockRecorder is the mock recorder for MockDatabasePinger.
type MockDatabasePingerMockRecorder struct {
	mock *MockDatabasePinger
}

// NewMockDatabasePinger creates a new mock instance.
func NewMockDatabasePinger(ctrl *gomock.Controller) *MockDatabasePinger {
	mock := &MockDatabasePinger{ctrl: ctrl}
	mock.recorder = &MockDatabasePingerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabasePinger) EXPECT() *MockDatabasePingerMockRecorder {
	return m.recorder
}

// PingContext mocks base method.
func (m *MockDatabasePinger) PingContext(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingContext", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// PingContext indicates an expected call of PingContext.
func (mr *MockDatabasePingerMockRecorder) PingContext(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingContext", reflect.TypeOf((*MockDatabasePinger)(nil).PingContext), arg0)
}
