-- +goose Up
CREATE TABLE IF NOT EXISTS gauges (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    value DOUBLE PRECISION NOT NULL
);
CREATE TABLE IF NOT EXISTS counters (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    value BIGINT NOT NULL
);

-- +goose Down
DROP TABLE IF EXISTS counters;
DROP TABLE IF EXISTS gauges;
